# --- !Ups
CREATE TABLE User
(
    ID       INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR(255),
    EMAIL    VARCHAR(255),
    PASSWORD VARCHAR(255)
);

CREATE TABLE Product
(
    ID          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    NAME        VARCHAR(255),
    DESCRIPTION TEXT,
    PRICE       DOUBLE
);

CREATE TABLE RecordInCart
(
    ID         INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    CART_ID    INTEGER,
    PRODUCT_ID INTEGER,
    QUANTITY   INTEGER
);

CREATE TABLE Cart
(
    ID      INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER
);


CREATE TABLE Order
(
    ID      INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    CART_ID INTEGER
);

CREATE TABLE Payment
(
    ID       INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    ORDER_ID INTEGER,
    IS_PAYED BOOLEAN,
    AMOUNT   DOUBLE
);

CREATE TABLE ItemScore
(
    ID          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    PRODUCT_ID  INTEGER,
    ITEM_SCORE  DOUBLE
);

CREATE TABLE ItemReview
(
    ID          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    USER_ID     INTEGER,
    PRODUCT_ID  INTEGER,
    REVIEW_TEXT TEXT
);

CREATE TABLE Discount
(
    ID          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    PRODUCT_ID  INTEGER,
    AMOUNT      DOUBLE
);

CREATE TABLE Login
(
    ID          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    USER_ID     INTEGER
    LOGIN_DATE  DATE
);

# --- !Downs
DROP TABLE User;
DROP TABLE Product;
DROP TABLE RecordInCart;
DROP TABLE Cart;
DROP TABLE Order;
DROP TABLE Payment;
DROP TABLE ItemReview;
DROP TABLE ItemScore;
DROP TABLE Discount;
DROP TABLE Login;
